FORMAT: 1A
HOST: http://api.mtngapp.com

# MTNG API
Proposed MTNG API

# MTNG API Root [/]
MTNG API entry point

## Affordances
+ self
+ 

## Retrieve the Entry Point [GET]
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <http:/api.mtngapp.com/>;rel="self"

    + Body

            {
                "_links": {
                    "self": { "href": "/" },
                }
            }